### ISSUE TITLE
Setting up consistency level and other datastax configurations

### ISSUE THREAD

**Issue by limadantas** [wise-coders/cassandra-jdbc-driver#3]
Is there any way to set the consistency level, timeout and other general datastax driver's configurations by using JDBC url or another one?

https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/dml/dmlConfigConsistency.html

**Comment by wise-coders** [comment]
We can add this property. I am not sure how to configure this in Java. Could you please have a look on the driver source code, maybe you can contribute?

**Comment by limadantas** [comment]
For sure! I'd looked at the code by I didn't found how to pass options and I was just asking to check. It will be nice to contribute, thanks.
